# Generated by Django 2.1.8 on 2019-05-13 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='like_acotr_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor_user_like_3', to='actors.Actor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='like_actor_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor_user_like_1', to='actors.Actor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='like_actor_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor_user_like_2', to='actors.Actor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='like_genre_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genre_user_like_1', to='movies.Genre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='like_genre_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genre_user_like_2', to='movies.Genre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='like_genre_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genre_user_like_3', to='movies.Genre'),
        ),
    ]
