# Generated by Django 2.1.8 on 2019-05-13 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('accounts', '0002_auto_20190513_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Me_you_similar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_sum_score', models.IntegerField(default=0)),
                ('you_sum_score', models.IntegerField(default=0)),
                ('movie_sum', models.IntegerField(default=0)),
                ('silmilar', models.FloatField(default=0.0)),
                ('me', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='me_similar', to=settings.AUTH_USER_MODEL)),
                ('same_genre_list', models.ManyToManyField(related_name='same_genre', to='movies.Genre')),
                ('you', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='you_similar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
