# Generated by Django 2.1.8 on 2019-05-13 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_me_you_similar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_scores', to='movies.Movie'),
        ),
    ]
