# Generated by Django 2.1.8 on 2019-05-14 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190513_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='me_you_similar',
            name='same_genre_list',
        ),
    ]
