# Generated by Django 2.1.8 on 2019-05-15 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_me_you_similar_same_genre_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('me', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_comment', to=settings.AUTH_USER_MODEL)),
                ('you', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='your_comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
