# Generated by Django 2.1.8 on 2019-05-13 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('twitter', models.CharField(blank=True, max_length=100)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('facebook', models.CharField(blank=True, max_length=100)),
                ('birthday', models.CharField(blank=True, max_length=40)),
                ('movies', models.ManyToManyField(blank=True, related_name='movie_actors', to='movies.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.CharField(blank=True, max_length=40)),
                ('actors', models.ManyToManyField(blank=True, related_name='actor_prizes', to='actors.Actor')),
                ('movies', models.ManyToManyField(blank=True, related_name='movie_prizes', to='movies.Movie')),
            ],
        ),
    ]
