# Generated by Django 2.1.8 on 2019-05-13 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='image',
        ),
        migrations.AddField(
            model_name='actor',
            name='imageurl',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
